Repository totaldebug/atomic-calendar-revive, pull requests merged in 2021-01, with the labels that each got.

#366 311 soft limit
  dist/atomic-calendar-revive.js
  docs/options/event-mode-options.md
  docs/options/main-options.md
  package.json
  src/defaults.ts
  src/index.ts
  src/localize/languages/en.json
  src/localize/languages/nb.json
  src/localize/languages/sv.json
  src/types.ts
Labels: feature

#371 docs: Add missing config options
  docs/options/main-options.md
Labels: documentation

#373 docs: update readme to new style
  .github/README.md
  .github/img/calendar-mode-allday.png
  .github/img/calendar-mode-today.png
  .github/img/events-mode.png
  .github/img/no-events.png
  README.md
  docs/faq.md
  docs/index.md
  docs/options/lang-options.md
Labels: documentation

#375 fix: resolves issue with show until
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
  tracker.json
Labels: bug

#376 feat: add fr translation (French)
  src/localize/languages/fr.json
Labels: language

#379 feat!: 374 disable calendar google link
  dist/atomic-calendar-revive.js
  docs/options/calendar-mode-options.md
  package.json
  src/defaults.ts
  src/index-editor.ts
  src/index.ts
  src/localize/languages/en.json
Labels: breaking, feature

#380 feat: change look of current day
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
Labels: feature

#382 fix: google calendar doesnt open from link
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
Labels: bug

#389 387 disablecallink missing from interface
  .babelrc
  dist/atomic-calendar-revive.js
  package.json
  rollup.config.js
  src/index-editor.ts
  src/index.ts
  src/localize/localize.ts
  src/style-editor.ts
  src/style.ts
  src/types.ts
  tracker.json
Labels: bug

#391 fix: lint errors resolved
  dist/atomic-calendar-revive.js
  package.json
  rollup.config.js
  src/index-editor.ts
  src/index.ts
  tracker.json
Labels: bug

#393 fixed CalDav on calendar mode
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
  tracker.json
Labels: type/bug

#394 hide private events without using blacklist
  dist/atomic-calendar-revive.js
  docs/options/main-options.md
  package.json
  src/defaults.ts
  src/index.ts
  src/types.ts
Labels: type/feature

#396 Update Quick Start documentation
  docs/quickstart.md
Labels: type/docs

#397 timesize and eventTitleSize font size not changing
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
Labels: type/bug
