Repository totaldebug/atomic-calendar-revive, pull requests merged in 2021-09, with the labels that each got.

#475 updating dependencies for module
  dist/atomic-calendar-revive.js
  package.json
  src/index-editor.ts
  src/index.ts
  src/style-editor.ts
  src/style.ts
Labels: dependencies

#478 lang: add Hungarian
  dist/atomic-calendar-revive.js
  docs/options/lang-options.md
  package.json
  src/locale.dayjs.ts
Labels: type/language

#479 land: added finnish
  dist/atomic-calendar-revive.js
  docs/options/lang-options.md
  package.json
  src/locale.dayjs.ts
Labels: type/language

#480 feat: ability to set description length
  dist/atomic-calendar-revive.js
  docs/options/main-options.md
  package.json
  src/index.ts
  src/types.ts
  tracker.json
Labels: type/feature

#483 Lang: added Slovak support
  dist/atomic-calendar-revive.js
  docs/options/lang-options.md
  package.json
  src/locale.dayjs.ts
  tracker.json
Labels: type/language

#488 feat: added new locale.language & fixed language bug
  README.md
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
  tracker.json
Labels: type/bug, type/feature

#489 fix: descLength causing events not to show
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
  tracker.json
Labels: type/bug

#491 lang: danish
  dist/atomic-calendar-revive.js
  docs/options/lang-options.md
  package.json
  src/locale.dayjs.ts
  src/localize/languages/da.json
  src/localize/localize.ts
  tracker.json
Labels: type/language
