Repository totaldebug/atomic-calendar-revive, pull requests merged in 2021-11, with the labels that each got.

#527 519 latest beta causes error
  .devcontainer/recommended-Dockerfile
  README.md
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
  src/types.ts
Labels: type/bug

#528 Update package.json
  package.json
Labels: semver/patch

#534 feat: add hebrew
  dist/atomic-calendar-revive.js
  docs/options/lang-options.md
  package.json
  src/locale.dayjs.ts
Labels: type/language

#535 fix: style declined events with no links (#530)
  dist/atomic-calendar-revive.js
  package.json
  src/index.ts
Labels: type/bug
